// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Cast: typeof import('./components/Cast.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    Episodes: typeof import('./components/Episodes.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Grid: typeof import('./components/Grid.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Heading: typeof import('./components/Heading.vue')['default']
    Posters: typeof import('./components/Posters.vue')['default']
    Rating: typeof import('./components/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    ShowCard: typeof import('./components/ShowCard.vue')['default']
    ShowInformation: typeof import('./components/ShowInformation.vue')['default']
    ShowSlider: typeof import('./components/ShowSlider.vue')['default']
  }
}
